name: Deploy website
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Setup Node.js 18
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18

    - name: install
      run: yarn

    - name: build
      run: node -v && npm run demo

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
